### ISSUE TITLE
On the number of parameters and CIFAR10/CIFAR100

### ISSUE THREAD

**Issue by bt-s** [leoTiez/dd2424#24]
- The number of parameters of our RCNN model seems to correspond to the number reported in the original paper.
- Increasing the number of filters has a drastic effect on the number of parameters, and thus on the complexity of the model.

1. As of yet, the performance on the CIFAR10 dataset is pretty miserable (i.e. ~49% after 5 iterations). Maybe Tensorboard and plotting gain provide insight into where we could tweak the model parameters to boost performance.

2. There are some issues with the CIFAR100 dataset. It achieves ~1% accuracy when using the gpu, and an error is thrown when using the cpu.

**Comment by leoTiez** [comment]
> i.e. ~49% after 5 iterations

That's not too bad. The recent implementation just uses more epochs and more update steps.

Relates to #28
